version: '3.9'


networks:
  default:


services:

  db:
    container_name: lavish-db
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - './private/.db:/var/lib/postgresql/data'

  server:
    container_name: lavish-server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 3001:3000
    env_file:
      - ./server/.env
    user: ${uid:-1000}:${gid:-1000}
